#!/bin/bash

# Script to help create Xcode project for RhinovateApp
# This will guide you through the process

echo "🚀 RhinovateApp Xcode Project Setup"
echo "====================================="
echo ""

# Check if Xcode is installed
if ! command -v xcodebuild &> /dev/null; then
    echo "❌ Xcode command line tools not found"
    echo "   Please install Xcode from the App Store first"
    exit 1
fi

echo "✅ Xcode found"
echo ""
echo "📝 Manual Setup Instructions:"
echo ""
echo "1. Open Xcode"
echo "2. File → New → Project"
echo "3. Choose 'iOS' → 'App'"
echo "4. Fill in:"
echo "   - Product Name: RhinovateApp"
echo "   - Team: (Select your team)"
echo "   - Organization Identifier: com.rhinovate (or your domain)"
echo "   - Interface: SwiftUI"
echo "   - Language: Swift"
echo "   - Minimum Deployment: iOS 13.0"
echo ""
echo "5. Save the project in a TEMPORARY location (we'll move files after)"
echo ""
echo "6. Once project is created:"
echo "   - Delete the default ContentView.swift and [AppName]App.swift files"
echo "   - Right-click on the project → Add Files to 'RhinovateApp'"
echo "   - Select ALL these folders/files from this directory:"
echo "     • Models/"
echo "     • Services/"
echo "     • Views/"
echo "     • AR/"
echo "     • RhinovateApp.swift"
echo "     • Info.plist"
echo "   - Make sure 'Copy items if needed' is CHECKED"
echo "   - Make sure 'Add to targets: RhinovateApp' is CHECKED"
echo ""
echo "7. Configure the project:"
echo "   - Select project in navigator"
echo "   - Select 'RhinovateApp' target"
echo "   - Go to 'Signing & Capabilities'"
echo "   - Select your development team"
echo ""
echo "8. Update Info.plist settings:"
echo "   - Target → Info tab"
echo "   - Verify camera and Face ID permissions are set"
echo ""
echo "9. Build Settings:"
echo "   - Ensure Swift version is 5.0+"
echo "   - Deployment target: iOS 13.0"
echo ""
echo "10. Connect a physical iPhone (ARKit requires real device)"
echo "11. Build and Run (⌘R)"
echo ""
echo "====================================="
echo ""
read -p "Press Enter when you've completed the setup, or Ctrl+C to cancel..."

echo ""
echo "✅ Setup complete! Your app should now work in Xcode."
echo ""
echo "📱 Remember:"
echo "   - ARKit only works on physical devices (iPhone X+)"
echo "   - Update APIClient.swift with your backend URL"
echo "   - Start the backend server before testing"

